services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER}
        UID: ${UID}
    volumes:
      - ..:/home/${USER}/project
    working_dir: /home/${USER}/project/pilot
    stdin_open: true
    tty: true
    stop_grace_period: 0s
