plugins {
    id 'java'
}

dependencies {
    implementation files('../../SysML-v2-Pilot-Implementation/org.omg.sysml.interactive/target/org.omg.sysml.interactive-0.54.0-SNAPSHOT-all.jar')
    implementation files('../../SysML-v2-Pilot-Implementation/org.omg.sysml.interactive/target/org.omg.sysml.interactive-0.54.0-SNAPSHOT-sources.jar')
}
